/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import javax.swing.JOptionPane;
import kontroler.ServerKontroler;

/**
 *
 * @author stefa
 */
public class FormaServer extends javax.swing.JFrame {

    private ServerKontroler serverKontroler;
    /**
     * Creates new form FormaServer
     */
    public FormaServer() {
        serverKontroler = new ServerKontroler();
        initComponents();
        btnZaustavi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        btnStart = new javax.swing.JButton();
        btnZaustavi = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKonfig = new javax.swing.JMenu();
        menuItemKonfig = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStart.setText("Pokreni server");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnZaustavi.setText("Zaustavi server");
        btnZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZaustaviActionPerformed(evt);
            }
        });

        menuKonfig.setText("Konfiguracija");

        menuItemKonfig.setText("Konfiguracija");
        menuItemKonfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKonfigActionPerformed(evt);
            }
        });
        menuKonfig.add(menuItemKonfig);

        jMenuBar1.add(menuKonfig);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        try {
            serverKontroler.pokreniServer();
            JOptionPane.showMessageDialog(this, "Server je uspesno pokrenut", "Pokrenut server", JOptionPane.INFORMATION_MESSAGE); 
            btnZaustavi.setEnabled(true);
            btnStart.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Server nije pokrenut", "Greska pri pokretanju servera", JOptionPane.ERROR_MESSAGE);
            System.out.println("Greska je ova: " +e.getMessage());
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZaustaviActionPerformed
        serverKontroler.zaustaviServer();
        JOptionPane.showMessageDialog(this, "Server je zaustavljen.", "Kraj", JOptionPane.INFORMATION_MESSAGE);
        btnStart.setEnabled(true);
        btnZaustavi.setEnabled(false);
    }//GEN-LAST:event_btnZaustaviActionPerformed

    private void menuItemKonfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKonfigActionPerformed
        FormaKonfiguracija fk = new FormaKonfiguracija();
        fk.setVisible(true);


    }//GEN-LAST:event_menuItemKonfigActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnZaustavi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuItemKonfig;
    private javax.swing.JMenu menuKonfig;
    // End of variables declaration//GEN-END:variables
}
