/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.putnik;
import domain.Kategorija;
import domain.Putnik;
import domain.VrstaKategorije;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroleri.KontrolerPutnik;
import listener.PutnikListener;
/**
 *
 * @author stefa
 */
public class KreirajPutnikForma extends javax.swing.JFrame {
    private KontrolerPutnik kontroler;
    private PutnikListener putnikListener;
    private Putnik putnik;
    /**
     * Creates new form KreirajPutnikForma
     */
    public KreirajPutnikForma() {
        putnik = null;
        kontroler = KontrolerPutnik.getInstance();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbBoxKategorija = new javax.swing.JComboBox<>();
        btnKreiraj = new javax.swing.JButton();
        btnOmoguciIzmenu = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnPromeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kreiraj putnika");

        jLabel1.setText("Ime:");

        txtIme.setEnabled(false);

        jLabel2.setText("Prezime:");

        txtPrezime.setEnabled(false);

        jLabel3.setText("ID:");

        txtId.setEnabled(false);

        jLabel4.setText("Email:");

        txtEmail.setEnabled(false);

        jLabel5.setText("Kategorija:");

        cmbBoxKategorija.setModel(new javax.swing.DefaultComboBoxModel<>(VrstaKategorije.values()));

        btnKreiraj.setText("Kreiraj");
        btnKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajActionPerformed(evt);
            }
        });

        btnOmoguciIzmenu.setText("Omoguci izmenu");
        btnOmoguciIzmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOmoguciIzmenuActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnPromeni.setText("Promeni");
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIme)
                    .addComponent(txtPrezime)
                    .addComponent(txtId)
                    .addComponent(txtEmail)
                    .addComponent(cmbBoxKategorija, 0, 200, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPromeni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKreiraj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOmoguciIzmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKreiraj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOmoguciIzmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbBoxKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPromeni, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajActionPerformed
        VrstaKategorije vrstaKategorija = (VrstaKategorije) cmbBoxKategorija.getSelectedItem();
        Kategorija kategorija = new Kategorija(-1, vrstaKategorija, null);
        kategorija.setId(kategorija.getIdByVrsta(vrstaKategorija));
        putnik = kontroler.kreirajPutnik(kategorija);
        if(putnik != null){
            JOptionPane.showMessageDialog(this, "Sistem je kreirao putnika", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            txtIme.setEnabled(true);
            txtPrezime.setEnabled(true);
            txtEmail.setEnabled(true);
            btnSacuvaj.setEnabled(true);
            btnKreiraj.setVisible(false);
            txtId.setText("" + kontroler.getIdPutnik());
        }
        else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira putnika", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnKreirajActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        VrstaKategorije vrstaKategorija = (VrstaKategorije) cmbBoxKategorija.getSelectedItem();
        Kategorija kategorija = new Kategorija(-1, vrstaKategorija, null);
        kategorija.setId(kategorija.getIdByVrsta(vrstaKategorija));
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        long id = kontroler.getIdPutnik();
        if (ime.isBlank() || prezime.isBlank() || email.isBlank() || kategorija == null) {
            JOptionPane.showMessageDialog(
                this,
                "Sistem ne moze da zapamti putnika",
                "Greska",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        boolean odgovor = kontroler.promeniPutnik(id, ime, prezime, email, kategorija);
        if(odgovor){
            JOptionPane.showMessageDialog(this, "Sistem je sacuvao putnika", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            if(putnikListener != null){
                putnikListener.putnikIzmenjen();
            }
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Sistem nije sacuvao putnika", "Neuspeh", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        long id = Long.parseLong(txtId.getText());
        VrstaKategorije vrstaKategorija = (VrstaKategorije) cmbBoxKategorija.getSelectedItem();
        Kategorija kategorija = new Kategorija(-1, vrstaKategorija, null);
        kategorija.setId(kategorija.getIdByVrsta(vrstaKategorija));
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String email = txtEmail.getText().trim();
        if (ime.isBlank() || prezime.isBlank() || email.isBlank() || kategorija == null) {
            JOptionPane.showMessageDialog(
                this,
                "Sistem ne moze da zapamti putnika",
                "Greska",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        boolean odgovor = kontroler.promeniPutnik(id, ime, prezime, email, kategorija);
        if(odgovor){
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio putnika", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            if(putnikListener != null){
                putnikListener.putnikIzmenjen();
            }
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Sistem nije zapamtio putnika", "Neuspeh", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void btnOmoguciIzmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOmoguciIzmenuActionPerformed
        txtPrezime.setEnabled(true);
        txtIme.setEnabled(true);
        txtEmail.setEnabled(true);
        //btnObrisi.setVisible(false);
        btnPromeni.setVisible(true);
    }//GEN-LAST:event_btnOmoguciIzmenuActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        try {
            kontroler.obrisiPutnika(putnik);
            JOptionPane.showMessageDialog(this, "Sistem je obrisao putnika", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
            if(putnikListener != null){
                putnikListener.putnikIzmenjen();
            }
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise putnika", "Neuspeh", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnObrisiActionPerformed
    public void setPutnik(Putnik putnik){
        this.putnik = putnik;
        txtId.setText(""+putnik.getId());
        txtIme.setText(putnik.getIme());
        txtPrezime.setText(putnik.getPrezime());
        txtEmail.setText(putnik.getEmail());
        cmbBoxKategorija.setSelectedItem(putnik.getKategorija().getVrstaKategorije());
        
        btnSacuvaj.setVisible(false);
        btnKreiraj.setVisible(false);
        btnPromeni.setVisible(true);
    }
    public void setPutnikListener(PutnikListener listener){
        putnikListener = listener;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KreirajPutnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KreirajPutnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KreirajPutnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KreirajPutnikForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KreirajPutnikForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOmoguciIzmenu;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox<VrstaKategorije> cmbBoxKategorija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
