/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domain.Operater;
import forme.karta.KreirajKartaForma;
import forme.karta.PrikaziKartaForma;
import forme.putnik.KreirajPutnikForma;
import forme.putnik.PrikaziPutnikForma;

/**
 *
 * @author stefa
 */
public class FormaGlavna extends javax.swing.JFrame {
    private PrikaziPutnikForma prikaziPutnikForma;
    private KreirajPutnikForma kreirajPutnikForma;
    private KreirajKartaForma kreirajKartaForma;
    private PrikaziKartaForma prikaziKartaForma;
    /**
     * Creates new form FormaGlavna
     */
    public FormaGlavna(Operater o) {
        initComponents();
        this.setLocationRelativeTo(null);
        lblUlogovan.setText("Dobrodosao " + o.getKorisnickoIme());
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPutnik = new javax.swing.JMenu();
        miKreirajPutnik = new javax.swing.JMenuItem();
        miPretraziPutnik = new javax.swing.JMenuItem();
        menuKarta = new javax.swing.JMenu();
        miKretirajKartu = new javax.swing.JMenuItem();
        miPretraziKartu = new javax.swing.JMenuItem();
        menuKvalifikacija = new javax.swing.JMenu();
        miUbaciKval = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Izaberite radnju");

        lblUlogovan.setText("jLabel1");

        menuPutnik.setText("Putnik");

        miKreirajPutnik.setText("Kreiraj");
        miKreirajPutnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajPutnikActionPerformed(evt);
            }
        });
        menuPutnik.add(miKreirajPutnik);

        miPretraziPutnik.setText("Pretrazi");
        miPretraziPutnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziPutnikActionPerformed(evt);
            }
        });
        menuPutnik.add(miPretraziPutnik);

        jMenuBar1.add(menuPutnik);

        menuKarta.setText("Karta");

        miKretirajKartu.setText("Kreiraj");
        miKretirajKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKretirajKartuActionPerformed(evt);
            }
        });
        menuKarta.add(miKretirajKartu);

        miPretraziKartu.setText("Pretrazi");
        miPretraziKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziKartuActionPerformed(evt);
            }
        });
        menuKarta.add(miPretraziKartu);

        jMenuBar1.add(menuKarta);

        menuKvalifikacija.setText("Kvalifikacija");

        miUbaciKval.setText("Ubaci");
        miUbaciKval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUbaciKvalActionPerformed(evt);
            }
        });
        menuKvalifikacija.add(miUbaciKval);

        jMenuBar1.add(menuKvalifikacija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblUlogovan, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(lblUlogovan)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKreirajPutnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajPutnikActionPerformed
        if(kreirajPutnikForma == null || !kreirajPutnikForma.isVisible()){
            kreirajPutnikForma = new KreirajPutnikForma();
        }
        
        if(prikaziPutnikForma != null){
            kreirajPutnikForma.setPutnikListener(prikaziPutnikForma);
        }
        kreirajPutnikForma.setVisible(true);
            
    }//GEN-LAST:event_miKreirajPutnikActionPerformed

    private void miPretraziPutnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziPutnikActionPerformed
        if (prikaziPutnikForma == null || !prikaziPutnikForma.isVisible()) {
            prikaziPutnikForma = new PrikaziPutnikForma();
        }
        if (kreirajPutnikForma != null) {
            kreirajPutnikForma.setPutnikListener(prikaziPutnikForma);
        }
        prikaziPutnikForma.setVisible(true);
    }//GEN-LAST:event_miPretraziPutnikActionPerformed

    private void miKretirajKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKretirajKartuActionPerformed
        if(kreirajKartaForma == null || !kreirajKartaForma.isVisible()){
            kreirajKartaForma = new KreirajKartaForma();
        }
        if(prikaziKartaForma != null){
            kreirajKartaForma.setKartaListener(prikaziKartaForma);
        }
        kreirajKartaForma.setVisible(true);
    }//GEN-LAST:event_miKretirajKartuActionPerformed

    private void miPretraziKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziKartuActionPerformed
        if(prikaziKartaForma == null || !prikaziKartaForma.isVisible()){
            prikaziKartaForma = new PrikaziKartaForma();
        }
        if(kreirajKartaForma != null){
            kreirajKartaForma.setKartaListener(prikaziKartaForma);
        }
        prikaziKartaForma.setVisible(true);
    }//GEN-LAST:event_miPretraziKartuActionPerformed

    private void miUbaciKvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUbaciKvalActionPerformed
        KreirajKvalifikacijaForma f = new KreirajKvalifikacijaForma();
        f.setVisible(true);
    }//GEN-LAST:event_miUbaciKvalActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblUlogovan;
    private javax.swing.JMenu menuKarta;
    private javax.swing.JMenu menuKvalifikacija;
    private javax.swing.JMenu menuPutnik;
    private javax.swing.JMenuItem miKreirajPutnik;
    private javax.swing.JMenuItem miKretirajKartu;
    private javax.swing.JMenuItem miPretraziKartu;
    private javax.swing.JMenuItem miPretraziPutnik;
    private javax.swing.JMenuItem miUbaciKval;
    // End of variables declaration//GEN-END:variables
}
